### ISSUE TITLE
Not working 0.0.6 — 0.0.8

### ISSUE THREAD

**Issue by davidhellmann** [martinherweg/modlr#4]
Reinstalled global
Reinstalled within the project

When I do `ferdi foo -m` nothing happens
![image](https://user-images.githubusercontent.com/764292/34695979-34db7b5a-f4cd-11e7-81a2-0aaac0f2ef3b.png)

And Global when I do `ferdi --help` 
```
# dh at davidhellmann.local in ~ [23:26:50]
→ ferdi --help
assert.js:43
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: missing path
    at Module.require (module.js:515:3)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dh/.nvm/versions/node/v8.4.0/lib/node_modules/ferdi/src/createModule.js:22:13)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
```

**Comment by davidhellmann** [comment]
Ups. My mistake. I've used the new ferdirc style for 0.0.8 within the < 0.0.8.  :)
